// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk6dGQf-zC-MvOWh9-5MJqwyplOjLEaAw',
    appId: '1:704483300946:web:263e9fc8fb91b7eb8b318b',
    messagingSenderId: '704483300946',
    projectId: 'findit-9d37d',
    authDomain: 'findit-9d37d.firebaseapp.com',
    storageBucket: 'findit-9d37d.firebasestorage.app',
    measurementId: 'G-QH6HE35EM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCVhpMG7lwlQpdQM0FGm6DOCtM1un0ED4',
    appId: '1:704483300946:android:c36324c6e6b86f498b318b',
    messagingSenderId: '704483300946',
    projectId: 'findit-9d37d',
    storageBucket: 'findit-9d37d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOiKOK44-a1nzbG0kSKqWLUefWtEZxtnI',
    appId: '1:704483300946:ios:df85bc265169e4cd8b318b',
    messagingSenderId: '704483300946',
    projectId: 'findit-9d37d',
    storageBucket: 'findit-9d37d.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOiKOK44-a1nzbG0kSKqWLUefWtEZxtnI',
    appId: '1:704483300946:ios:df85bc265169e4cd8b318b',
    messagingSenderId: '704483300946',
    projectId: 'findit-9d37d',
    storageBucket: 'findit-9d37d.firebasestorage.app',
    iosBundleId: 'com.example.findit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk6dGQf-zC-MvOWh9-5MJqwyplOjLEaAw',
    appId: '1:704483300946:web:673701c992cbd1008b318b',
    messagingSenderId: '704483300946',
    projectId: 'findit-9d37d',
    authDomain: 'findit-9d37d.firebaseapp.com',
    storageBucket: 'findit-9d37d.firebasestorage.app',
    measurementId: 'G-GJSFH9G4HG',
  );
}
